# Generated by Django 2.2.10 on 2021-03-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('client', 'date')},
        ),
    ]
