# Generated by Django 2.0.12 on 2021-03-14 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210312_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_mime_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('file_last_modified', models.CharField(max_length=100)),
                ('file_hash', models.CharField(max_length=66)),
                ('transaction_hash', models.CharField(default='', max_length=256)),
                ('transaction_created_at', models.DateTimeField(auto_now=True)),
                ('has_proof', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Client')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Employee')),
            ],
        ),
    ]
