# Generated by Django 2.0.12 on 2021-03-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='file_last_modified',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='has_proof',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='transaction_created_at',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='transaction_hash',
        ),
        migrations.AddField(
            model_name='operation',
            name='previous_hash',
            field=models.CharField(default='', max_length=255),
        ),
    ]
