# Generated by Django 3.2.12 on 2022-04-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220426_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='doc',
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
    ]
